### ISSUE TITLE
公共房间页面优化

### ISSUE THREAD

**Issue by mantou132** [mantou132/nesbox#212]
- 自动刷新不增加，只更新
- 页面添加筛选（搜索？）、刷新功能

**Comment by hehehai** [comment]
💬
- 这里好像没有分页？
- 搜索的话（加入房间），可能需要一个房间名称，或房间号或房主名称
- 排序问题（最新创建，最早创建）
- 房间总数

**Comment by mantou132** [comment]
@hehehai 

NESBox 的所有接口都没有分页，数据都不多而且也不会无限增长，以后可能需要默认不公开房间。

为了简化操作，所以房间没有名称，房间号虽然有，但是是用户无感知的。现在只能搜索房主名称和房间当前游戏名称了。

排序确实要做，而且不止这个接口需要加，还有用户收藏、所有游戏等。

房间总数，在线人数可以显示，不过需要合适的 UI 来展示。

**Comment by mantou132** [comment]
修改如下：

- 按创建时间降序
- 复合搜索支持房间搜索

<img width="1136" alt="Screen Shot 2022-09-10 at 07 01 11" src="https://user-images.githubusercontent.com/3841872/189456763-5b48e825-c9a2-4e76-9c99-4b60b3698b73.png">
