### ISSUE TITLE
键盘绑定上下左右键似乎无效

### ISSUE THREAD

**Issue by AlexanderMisel** [mantou132/nesbox#213]
尝试将上下左右绑定为键盘的上下左右，似乎无法正常操纵游戏。绑定字母按键似乎正常。

**Comment by mantou132** [comment]
方向键默认绑定到手柄 2 了，也就是同一台电脑可以操纵 p1 p2，把手柄 2 的绑定成其他按键试试

<img width="522" alt="Screen Shot 2022-09-09 at 13 00 07" src="https://user-images.githubusercontent.com/3841872/189275067-b8d931a4-341d-4960-97b2-62666edacd10.png">

**Comment by AlexanderMisel** [comment]
好吧，谢谢

**Comment by hehehai** [comment]
@mantou132 hi，手柄这里或许可以说明一下（我在第一次使用的时候，设置时以为我真的需要一个手柄才可以玩 😅 而快捷键才是我需要设置的电脑按键，尝试后，才发现手柄按钮可以点击设置按键），你觉得怎么样。

**Comment by mantou132** [comment]
@hehehai 感谢反馈，这里小标题改成“手柄 1 - 键盘映射” 不知能否解决用户的困惑。

另外加个映射冲突提示。

**Comment by mantou132** [comment]
现在使用手柄1 的设置覆盖手柄2 的设置，解决了楼主的问题。

https://github.com/mantou132/nesbox/commit/4ca84d55144af0b1ee54e5014d5dfcc09b83901c#diff-a75d8fabcffcd7406191470d162ddd161c0b69a0b02b8711d7d985e72dd764a7
