### ISSUE TITLE
避免默认 nickname 暴露用户名称，例如邮箱、名字

### ISSUE THREAD

**Issue by mantou132** [mantou132/nesbox#214]
默认昵称使用多个词语随机组合？

**Comment by hehehai** [comment]
房主名称吗？或许可以脱敏下 xx****xx，要不就组合随机

修饰-名词-随机字符
- 修饰：[可爱的，机智的]
- 名词：[冬瓜，小王]
- 随机字符：[Xzz, 970]

💬 房间搜索的时候，支持房主搜索的话，要完全匹配，还是模糊（模糊的话如何展示）🤔

**Comment by mantou132** [comment]
对，就是用户显示名称，还显示在游戏评论上。

脱敏显示不好看；随机词组合不好支持多语言。

搜索的话跟 `ctrl+k` 的方法一致就好（分词之后有一个被包含就匹配）,所有一个搜索栏（工具栏）没其他需要需要特殊展示吧

**Comment by mantou132** [comment]
暂时简单点处理，截取 `@` 前面的字符
