### ISSUE TITLE
Mac os10.13.6无法运行

### ISSUE THREAD

**Issue by kingxiaofire** [mantou132/nesbox#215]
下载dmg安装之后，无法打开

**Comment by hehehai** [comment]
@kingxiaofire hi, 我这边 Mac Intel 安装 [NESBox_1.0.6_x64.dmg](https://github.com/mantou132/nesbox/releases/download/v1.0.6/NESBox_1.0.6_x64.dmg) 是正常的。是闪退吗？

Tauri 应用程序在 macOS 中运行所需的最低操作系统版本是 10.13，这里还不知道 nesbox 是不是使用了更改版本的特性。

**Comment by mantou132** [comment]
你可以使用 Chrome 将 NESBox 安装成 PWA。

很可能是 Web 兼容性的问题：Tuari 使用系统 WebView ，也就是 Safari，Web 前端使用了 [gemjs](https://gemjs.org/)，只支持较新的浏览器

**Comment by kingxiaofire** [comment]
大家好，我使用的就是NESBox_1.0.6_x64.dmg，安装之后，点击无法运行，表现为，docker栏有图标，但是不显示任何界面。
