### ISSUE TITLE
Need Help: how to add games in DB

### ISSUE THREAD

**Issue by hehehai** [mantou132/nesbox#217]
**Is your feature request related to a problem? Please describe.**

I have run the program 🥰, but there is no game information in the database. I don't know how to add a new game for development testing.

**Describe the solution you'd like**

Hope

- A tutorial(description) on how to install a game
- simple game data (can init the db games)

**Comment by mantou132** [comment]
https://github.com/mantou132/nesbox/tree/master/packages/server#manage-games
