### ISSUE TITLE
About nes Failed to construct 'URL': Invalid URL

### ISSUE THREAD

**Issue by hehehai** [mantou132/nesbox#219]
**Describe the bug**

After the creation of the room page jumps, an error pops up.

<img width="1681" alt="image" src="https://user-images.githubusercontent.com/12692552/189474449-3171c5a1-1042-4fdc-b2c8-cba8d95cc42e.png">

devtool
<img width="1122" alt="image" src="https://user-images.githubusercontent.com/12692552/189474456-8955f0c6-71a0-419e-814e-1ad7f62b8681.png">

**To Reproduce**
env

- server: all DB data ready, server ready
- web: dev server ready
- nes-pkg: successful build

❗️all terminal no Error
❗️the game data from [sql file](https://github.com/mantou132/nesbox/releases/download/0.0.1/games.sql)
❗️no code changed（only set .env）

**Expected behavior**

nes game working

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: chrome
 - Version: latest code

**Comment by mantou132** [comment]
有尝试清除过 vite 缓存吗？

没遇到过。

**Comment by hehehai** [comment]
@mantou132 ok solved, try reinstall `node_modules` in `packages/webapp`.
