### ISSUE TITLE
搜索输入，未输入值的时候会出现暂无数据

### ISSUE THREAD

**Issue by hehehai** [mantou132/nesbox#221]
<img width="687" alt="image" src="https://user-images.githubusercontent.com/12692552/189601861-d0fc12b7-b30e-4f7d-8ed9-445a7788594f.png">

预期：
未输入值的时候不显示暂无数据

（之前是这种行为，更新 [#db9e8dde832f797248cb7fdd41a3014a73042717](https://github.com/mantou132/nesbox/commit/db9e8dde832f797248cb7fdd41a3014a73042717) 后出现 ）

🤔 这个问题可以这么解决

https://github.com/mantou132/nesbox/blob/db9e8dde832f797248cb7fdd41a3014a73042717/packages/webapp/src/modules/search.ts#L318-L322
```
<div class="result">
        ${search
          ? html`<dy-options
              class="options"
              .options=${options.length ? options : [{ label: locale.noData }]}
            ></dy-options>`
          : ''}
        <div class="placeholder" @click=${toggoleSearchState}></div>
</div>
```

**Comment by hehehai** [comment]
可以的话，我可以提交个 pr。

**Comment by mantou132** [comment]
感谢提交的 PR，但这个 PR 有个问题没有解决，所以没有合并，另一个原因是 `master` 频繁更新会触发 bug #8 ，所以默认分支调整成 `dev` 了。

我刚刚给搜索结果加了个快捷键，修复了这个问题。
