### ISSUE TITLE
搜索结果支持键盘事件

### ISSUE THREAD

**Issue by hehehai** [mantou132/nesbox#224]
<img width="683" alt="image" src="https://user-images.githubusercontent.com/12692552/189608542-e985cc0e-6fca-4685-8148-df2c7794208c.png">

描述
- 键盘 up，down 事件，来调整结果项 focus
- 键盘 enter 事件，触发点击操作

**Comment by mantou132** [comment]
当前是 tab + space/enter 操作。

可以考虑支持方向键

**Comment by mantou132** [comment]
可能用一个临时快捷键更好，比如 `command+1-9`

**Comment by hehehai** [comment]
> 可能用一个临时快捷键更好，比如 `command+1-9`

嗯，确实（想法是两个都支持会更好）
- `up`，`down` 用户使用习惯（虽然有 tab 支持）
- `command+1-9` 可以直接触发进入（不需要 enter）

🤔 提示（想到两种）
**直接高亮热键**（移动端不展示）
<img width="663" alt="image" src="https://user-images.githubusercontent.com/12692552/189630218-d75017cb-846e-42ea-87de-686337d445fc.png">

**底部说明**
<img width="767" alt="image" src="https://user-images.githubusercontent.com/12692552/189630380-94dcc50b-8a92-422c-8fff-7d283def508b.png">
