### ISSUE TITLE
为游戏应用增加 LOGO，用于跳转到官网

### ISSUE THREAD

**Issue by hehehai** [mantou132/nesbox#225]
功能：
- 跳转到官网（应用下载等）

实现：
**logo**
<img width="404" alt="image" src="https://user-images.githubusercontent.com/12692552/189609814-10b66016-ead2-4a78-ae3c-9ce6f5e85150.png">

**个人信息下拉**
<img width="261" alt="image" src="https://user-images.githubusercontent.com/12692552/189609868-7713d420-fcd1-4c14-b27f-07b7e4421bf7.png">

**Comment by mantou132** [comment]
感觉应用内导航没有必要，下拉菜单可以加个。

**Comment by hehehai** [comment]
> 感觉应用内导航没有必要，下拉菜单可以加个。

ok，我可以负责这个修改吗？

实施
- 在添加游戏下方新增 “游戏官网” 链接按钮
- i18n 支持

**Comment by mantou132** [comment]
当然可以了。

关于官网页面有个这样的设定：PWA/桌面端 APP 内不希望显示官网页面，所以这里可能要使用 `open('/')` 才行。
