### ISSUE TITLE
帮助中心页面

### ISSUE THREAD

**Issue by hehehai** [mantou132/nesbox#226]
### 位置：
**官网导航**
<img width="377" alt="image" src="https://user-images.githubusercontent.com/12692552/189610281-69e02938-e741-4398-aa15-f4a685bfbdab.png">

**游戏导航**
<img width="563" alt="image" src="https://user-images.githubusercontent.com/12692552/189610149-3f6f141d-3eac-4ba4-bac4-f607f38e05fb.png">

**搜索提示**
<img width="642" alt="image" src="https://user-images.githubusercontent.com/12692552/189610358-d07759d1-8843-4c09-8957-56df30387c7b.png">

**个人信息下拉**
<img width="247" alt="image" src="https://user-images.githubusercontent.com/12692552/189610444-c1de0ea7-f1d5-479c-be19-24614a4a8393.png">

### 页面内容：
- 应用下载安装（电脑，手机，电视，网页等）
- 游戏操作
- 游戏术语（如：金手指）
- 反馈，常见问题等

**Comment by mantou132** [comment]
这个工作量比较大，🤣

- 页面设计
- 文档组织
- Flutter 版本的完善+发布

我未来一段时间将完善 Flutter 版本（现在主要也是卡在 UX 设计上，没玩过 XBox，不知道怎么交互的）。

**Comment by hehehai** [comment]
> 这个工作量比较大，🤣
> 
> * 页面设计
> * 文档组织
> * Flutter 版本的完善+发布
> 
> 我未来一段时间将完善 Flutter 版本（现在主要也是卡在 UX 设计上，没玩过 XBox，不知道怎么交互的）。

😆 嗯，明白的。

你看这样行不行
1. 我先把这个 issue 关了。
2. 之后有相关的帮助页面的信息（主要是 常见问题）都可以用该 issue 做关联。
3. 待收集一部分常见问题后，可以汇总一下，再考虑如何开放。

@mantou132 你觉得怎么样？

**Comment by mantou132** [comment]
👌

**Comment by hehehai** [comment]
## 浏览器应用

## 安装（Chrome 浏览器）
<img width="1303" alt="image" src="https://user-images.githubusercontent.com/12692552/192123219-2c6eaf1d-e4bd-49ed-93cc-7a712be99460.png">

点击安装

<img width="1312" alt="image" src="https://user-images.githubusercontent.com/12692552/192123239-aefd5956-0fd6-4017-b378-844197428d30.png">

## 卸载

<img width="1196" alt="image" src="https://user-images.githubusercontent.com/12692552/192123267-c7702789-c186-4ca2-8e60-2587acc0333c.png">

<img width="1197" alt="image" src="https://user-images.githubusercontent.com/12692552/192123275-fafbafaa-a078-4715-b90b-26b73cb31180.png">

**Comment by hehehai** [comment]
## 忘记密码了怎么办？

2022-09-25: v1.0.6 暂时不支持忘记密码找回，建议重新注册账号
