### ISSUE TITLE
好友添加，不存在的用户提示”用户不存在“

### ISSUE THREAD

**Issue by hehehai** [mantou132/nesbox#227]
### 问题
当前添加好友，无论用户是否存在，都不显示发送成功。建议不存在的用户显示”用户不存在“

<img width="376" alt="image" src="https://user-images.githubusercontent.com/12692552/189611346-6d639056-489e-49b6-8186-82cc6b7c9e42.png">
<img width="195" alt="image" src="https://user-images.githubusercontent.com/12692552/189611397-1bbb97ca-2657-487f-8ed7-d11e2cf7d96b.png">

### 调整
<img width="380" alt="image" src="https://user-images.githubusercontent.com/12692552/189611528-489c1bba-98be-4013-8bae-aac7746bfccf.png">

- 点击确认时，发送请求，确认用户是否存在，不存在显示”用户不存在“
- Modal 不关闭

**Comment by mantou132** [comment]
这是故意这么设计的。不希望后端直接暴露其他用户的用户名。

就像用户名错误，报错用户名或者密码错误一样。

**Comment by hehehai** [comment]
> 这是故意这么设计的。不希望后端直接暴露其他用户的用户名。
> 
> 就像登录时用户名错误，报错“用户名或者密码错误”一样。

嗯，明白的。这里的调整实际依然没有直接保留用户名。

场景 1
1. 用户 a 想要添加用户 b 为好友
2. 点击添加，输入 b
3. 点击确认，好友请求发送成功

场景 2
1. 用户 a 想要添加用户 b 为好友
2. 点击添加，输入 c（很明显它没有输入正确的用户名称）
3. 点击确认
4. “OH，该用户不存在”。好吧，用户 a 发现他输入错误了
5. 修改后，点击确认，好友请求发送成功

场景 3
1. 用户 a 想要添加用户 b 为好友
2. 点击添加，输入 c（很明显它没有输入正确的用户名称）
3. 点击确认，好友请求发送成功（虽然错了，但刚好 用户 c 是存在的）

🤔 这里没有模糊匹配

场景 3 的话，我想或许可以有一个已经发送的好友请求的展示（在没有确认前，可以取消发送）

@mantou132 你认为怎么样 ?

**Comment by mantou132** [comment]
现在更大的问题是用户添加好友时会使用显示名称。而且并不会报错。
