### ISSUE TITLE
对高刷新率的支持有问题

### ISSUE THREAD

**Issue by IsumiAlice** [mantou132/nesbox#235]
对于高刷新率（超过60），游戏中右下角显示帧率等于荧幕的刷新率，于是游戏会以 '荧幕刷新率/60' 的倍速运行
同时也导致了声音不同步

尝试在 Windows 系统设置中改为 60 帧后可以正常运行
希望可以适配一下，或是增加个锁定 60 帧运行的功能

**Comment by mantou132** [comment]
谢谢 你的反馈，以前根本没有遇到个这个问题，设置都没意识到 Web 的 API 会受显示器刷新率影响。

尝试跳过了一些帧刷新，不知道效果怎么养。

你可以试一下吗？

**Comment by IsumiAlice** [comment]
可以正常玩了，感谢修复💕
