### ISSUE TITLE
热血格斗传说汉化

### ISSUE THREAD

**Issue by chenwen97** [mantou132/nesbox#272]
![热血格斗传说汉化](https://github.com/mantou132/nesbox/assets/25432732/c24f7dc0-2609-47dc-884c-2d17fc4ce11d)
[热血格斗传说汉化.zip](https://github.com/mantou132/nesbox/files/11495436/default.zip)

**Comment by mantou132** [comment]
已经将汉化的 rom 更新到 https://github.com/mantou132/nesbox/issues/1

NESBox 支持中/英/日 3 种语言，对应各自语言的 ROM、标题、截图、简介。
