### ISSUE TITLE
热血篮球汉化

### ISSUE THREAD

**Issue by chenwen97** [mantou132/nesbox#274]
![热血篮球汉化](https://github.com/mantou132/nesbox/assets/25432732/46a5cf6c-4544-4c5f-bb63-2e8b8c106b51)
[热血篮球汉化.zip](https://github.com/mantou132/nesbox/files/11495457/default.zip)

**Comment by mantou132** [comment]
更新到 https://github.com/mantou132/nesbox/issues/6
