### ISSUE TITLE
前端更新后在老版本切换路由会资源加载失败

### ISSUE THREAD

**Issue by mantou132** [mantou132/nesbox#8]
vercel 增量部署？

**Comment by zhuweiyou** [comment]
vite config 设置 `build: { emptyOutDir: false }`  旧版本文件就保留下来了.

应该需要在 CI 配置一下: 缓存 dist 目录

**Comment by zhuweiyou** [comment]
https://vercel.com/docs/build-output-api/v3#build-output-configuration/supported-properties/cache

**Comment by mantou132** [comment]
@zhuweiyou 谢谢，我还以为 vercel 会自动为 ouput 目录缓存。

**Comment by zhuweiyou** [comment]
我也没用过, 但是我感觉这个配置应该是放在 `vercel.json` 里的.  得看 build log 才知道是否生效

**Comment by mantou132** [comment]
他那个文档不太确定是不是说的这个。

我刚刚试着加了：
```

{
  "version": 3,
  "cache": ["packages/webapp/dist"]
}
```
结果 404 了，似乎是直接发布 `.outputs` 中的文件，看他的例子都是放在 `outputs` 中的

**Comment by mantou132** [comment]
现在使用了 cloudflare ，默认配置，应该有缓存
